### ISSUE TITLE
Error cuando ejecuto

### ISSUE THREAD

**Issue by oneictstudent** [apscreativas/laravel8-docker#1]
Buen dia, soy nuevo en docker, estaba ejecutando tu codigo y me aparece este error:

#37 162.2 Installing '/usr/local/lib/php/extensions/no-debug-non-zts-20210902/memcached.so'
#37 164.5 install ok: channel://pecl.php.net/memcached-3.1.5
#37 164.5 configuration option "php_ini" is not set to php.ini location
#37 164.5 You should add "extension=memcached.so" to php.ini
#37 170.0 No releases available for package "pecl.php.net/imagick"
#37 170.0 install failed
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c pecl channel-update pecl.php.net     && pecl install memcached   
  && pecl install imagick     && docker-php-ext-enable memcached     && docker-php-ext-enable imagick]: exit code: 1

Gracias por tu ayuda

**Comment by apscreativas** [comment]
Lo hemos probado en Linux, Windows y Mac y no encontramos dicho error.

Aún asi se agrego la extensión que pide en php.ini ..
